#!/usr/bin/env python

# Converts transmittance T(E) to I-V curve

import sys

usage = "\nUsage:  t2iv  trans-file\n"

if len(sys.argv) != 2:
    print usage
    sys.exit(1)

f_trans = sys.argv[1]


### Read transmittance data
f = open(f_trans, "r")

Transmittance = []
for line in f:
    E, T = line.split()

    Transmittance.append([float(E), float(T)])

f.close()

#print Transmittance


### Integrate transmittance to obtain current

Npts = len(Transmittance)

Current = []
integral = 0
for i in range(1, Npts):
    E1 = Transmittance[i-1][0]
    E2 = Transmittance[i][0]
    T1 = Transmittance[i-1][1]
    T2 = Transmittance[i][1]

    t = 0.5 * (T1 + T2)
    e = 0.5 * (E2 + E1)
    dE = E2 - E1

    integral += t * dE

    Current.append([e, integral])

#print Current    

f_cur = "i-v.txt"

f = open(f_cur, "w")

for i in range(len(Current)):
    u = Current[i][0]
    j = Current[i][1]
    f.write("%10.6f   %10.10f\n" % (u, j))

f.close()
